---
- name: "Add a new user named {{ sysadmin_user }}"
  ansible.builtin.user:
    name: "{{ sysadmin_user }}"
    shell: "{{ sysadmin_shell }}"
    password: "{{ sysadmin_password }}"

- name: Add '{{ sysadmin_user }}' to the sudoers
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ sysadmin_user }}"
    content: "{{ sysadmin_user }}  ALL=(ALL)  NOPASSWD: ALL"
    mode: 0644
  when: sysadmin_issudoer

- name: Remove '{{ sysadmin_user }}' from sudoers
  ansible.builtin.file:
    path: "/etc/sudoers.d/{{ sysadmin_user }}"
    state: absent
  when: not sysadmin_issudoer

- name: Set up multiple authorized keys
  ansible.posix.authorized_key:
    user: "{{ sysadmin_user }}"
    state: present
    key: '{{ item }}'
    path: ~/.ssh/authorized_keys
  with_items: '{{ sysadmin_keys }}'

- name: Copy files using variable `sysadmin_files`
  ansible.builtin.copy:
    src: '{{ item.file }}'
    dest: '{{ item.dest }}'
    owner: '{{ sysadmin_user }}'
    group: '{{ sysadmin_user }}'
    mode: '0644'
  with_items: '{{ sysadmin_files }}'