---
sysadmin_user: ansible
sysadmin_password: example
sysadmin_shell: '/bin/bash'
sysadmin_keys: 
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDojuf5y2YKjti1YR+AaVmra1iVZW3xomlrVBPvJveG1ucGo6HV8MM73R8Ssvcj3zpOdzgF5CmgUYRqj9ksAXfnVM2J/Z1I93SqIx0boRgh09bhTcW7viS7Uy9DBvI6Qcj4OC9oYS5BDgFi94kX7EpWO4qISY0FysegxCrKWcOrvCoWM2mGNy4sfsSW7vTxOVqobFXqBaFis5KfXr9BxIX5BSR1/MKxGeAQxuCrhAFIf26FnG6la9+Q7nnT402Xoo1xmp5HQXzl1kyNCs8YvHcvZreQfCoylKrU2ZoG9WClQOUxlktqNf9Kc5gfYU+QiWMZsdj/sGRmSNg49zQnLb9lSir8P4IGgfkvtKAonpSrom9Qs5k0YtW5u+oCuL9jW1Q9k2HA53e+5jv3l32f/7O4ob/Rk6wTUkkqAomn4zPqttpf6OPxiEJi45ACiBWOt6oCegUk0hwlLCUALrDYrl/o0yFJrqwEE/2omVOf/6NnwJ4kYEvSIuO9hZF/zmw5i9M=