---
- name: Verify
  hosts: all
  gather_facts: false
  become: true
  vars_files:
    - vars.yml
  tasks:
  - name: "Is user {{ sysadmin_user }} added"
    getent:
      database: passwd
      key: "{{ sysadmin_user }}"
    register: getent_user

  - assert:
      name: Ensure getent for user is correct
      that: 
        - getent_user.ansible_facts.getent_passwd[sysadmin_user] is defined
        - getent_user.ansible_facts.getent_passwd[sysadmin_user][0] == 'x'
        - getent_user.ansible_facts.getent_passwd[sysadmin_user][1] == '1000'
        - getent_user.ansible_facts.getent_passwd[sysadmin_user][2] == '1000'
        - getent_user.ansible_facts.getent_passwd[sysadmin_user][4] == '/home/{{ sysadmin_user }}'
        - getent_user.ansible_facts.getent_passwd[sysadmin_user][5] == '{{ sysadmin_shell }}'
